<?php

namespace SkyengBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorRepository extends EntityRepository
{
    /**
     * @param Word $word
     * @param      $answer
     *
     * @return Error
     */
    public function findByWordAndAswer(Word $word, $answer)
    {
        $error = $this->createQueryBuilder('wt')
            ->where('wt.word = :word')
            ->andWhere('wt.answer = :answer')
            ->setParameters([
                'word' => $word,
                'answer' => $answer
            ])
            ->getQuery()
            ->getOneOrNullResult()
            ;

        if (!$error) {
            $error = new Error();
            $error->setWord($word);
            $error->setAnswer($answer);

        }

        return $error;
    }
}
